---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
- Nine/Cache/
- Nine/Containers/assets/
- Nine/Collections/Collection.php
- Nine/Database/Console/
- Nine/Containers/DI.php
- Nine/Support/Inflector.php
