---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
      - ffae9999aabb999c2242664dbca5f299
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
- Nine/Cache/
- Nine/Containers/assets/
- Nine/Containers/DI.php
- Nine/Containers/PhpStormMeta.php
- Nine/Collections/Collection.php
- Nine/Database/Console/
- Nine/Support/Inflector.php
- Nine/Support/helpers.php
